# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :adhoc_build_number do
    # Increment build number
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "../adhoc/Unity-iPhone.xcodeproj"
    )
  end
  lane :appstore_build_number do
    # Increment build number
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "../appstore/Unity-iPhone.xcodeproj"
    )
  end
  lane :adhoc_upload do
    # Build and upload to TestFlight
    upload_to_testflight(
      ipa: "../adhoc-build/build/D1.ipa",
      skip_waiting_for_build_processing: true
    )
  end
  lane :appstore_upload do
    # Build and upload to TestFlight
    upload_to_testflight(
      ipa: "../appstore-build/build/D1.ipa",
      skip_waiting_for_build_processing: true
    )
  end
end

